/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ConnectFourGUI;
import processing.core.PApplet;

/**
 * the start of the program
 */
public class App extends PApplet {
    /**
     * @param args not used
     * starts the gui
     */
    public static void main(String[] args) {
         Setup draw = new Setup(1080, 720);
         PApplet.runSketch(new String[]{""}, draw);
    }
}
